"""add_political_social_media_models

Revision ID: political_models
Revises: 1a31ce608336
Create Date: 2025-03-18 22:34:36.701503

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'political_models'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types
    op.create_table('politicalentity',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('country', sa.String(length=100), nullable=True),
        sa.Column('region', sa.String(length=100), nullable=True),
        sa.Column('political_alignment', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('id', postgresql.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_politicalentity_name'), 'politicalentity', ['name'], unique=False)
    
    op.create_table('socialmediaaccount',
        sa.Column('platform', sa.String(length=50), nullable=False),
        sa.Column('platform_id', sa.String(length=255), nullable=False),
        sa.Column('handle', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('url', sa.String(length=2083), nullable=True),
        sa.Column('verified', sa.Boolean(), nullable=False),
        sa.Column('follower_count', sa.Integer(), nullable=True),
        sa.Column('following_count', sa.Integer(), nullable=True),
        sa.Column('political_entity_id', postgresql.UUID(), nullable=False),
        sa.Column('id', postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['political_entity_id'], ['politicalentity.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_socialmediaaccount_platform_id'), 'socialmediaaccount', ['platform_id'], unique=False)
    
    op.create_table('entityrelationship',
        sa.Column('relationship_type', sa.String(length=50), nullable=False),
        sa.Column('strength', sa.Float(), nullable=False),
        sa.Column('last_updated', sa.DateTime(), nullable=False),
        sa.Column('source_entity_id', postgresql.UUID(), nullable=False),
        sa.Column('target_entity_id', postgresql.UUID(), nullable=False),
        sa.Column('id', postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['source_entity_id'], ['politicalentity.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_entity_id'], ['politicalentity.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('strength >= 0.0 AND strength <= 1.0', name='check_strength_range')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entityrelationship')
    op.drop_index(op.f('ix_socialmediaaccount_platform_id'), table_name='socialmediaaccount')
    op.drop_table('socialmediaaccount')
    op.drop_index(op.f('ix_politicalentity_name'), table_name='politicalentity')
    op.drop_table('politicalentity')
    # ### end Alembic commands ###
